// Mobile Menu Toggle
document.addEventListener('DOMContentLoaded', function() {
    const mobileMenu = document.querySelector('.mobile-menu');
    const navLinks = document.querySelector('.nav-links');
    
    mobileMenu.addEventListener('click', function() {
        navLinks.classList.toggle('active');
    });
    
    // Close mobile menu when clicking on a link
    document.querySelectorAll('.nav-links a').forEach(link => {
        link.addEventListener('click', () => {
            navLinks.classList.remove('active');
        });
    });
    
    // Smooth scrolling for anchor links
    document.querySelectorAll('a[href^="#"]').forEach(anchor => {
        anchor.addEventListener('click', function (e) {
            e.preventDefault();
            const target = document.querySelector(this.getAttribute('href'));
            if (target) {
                target.scrollIntoView({
                    behavior: 'smooth',
                    block: 'start'
                });
            }
        });
    });
    
    // AI Content Generator
    const generateBtn = document.getElementById('generateContent');
    const aiTopic = document.getElementById('aiTopic');
    const aiOutput = document.getElementById('aiOutput');
    
    generateBtn.addEventListener('click', function() {
        const topic = aiTopic.value.trim();
        
        if (!topic) {
            aiOutput.innerHTML = '<p style="color: #ef4444;">Please enter a topic first!</p>';
            return;
        }
        
        // Show loading state
        aiOutput.innerHTML = '<p><i class="fas fa-spinner fa-spin"></i> Generating AI content...</p>';
        
        // Simulate AI content generation (in a real app, this would call an API)
        setTimeout(() => {
            const aiResponses = [
                `Based on "${topic}", here's an insightful analysis: This emerging technology is transforming industries by automating complex processes and enabling data-driven decision making. Companies adopting these solutions typically see a 30-50% improvement in operational efficiency.`,
                
                `AI-powered solutions for "${topic}" are revolutionizing how businesses operate. Key benefits include enhanced customer experiences, reduced operational costs, and the ability to scale rapidly. The market for such technologies is expected to grow exponentially over the next 5 years.`,
                
                `When it comes to "${topic}", artificial intelligence offers unprecedented opportunities. Our analysis shows that organizations implementing AI strategies in this area achieve 40% faster time-to-market and 35% higher customer satisfaction rates compared to traditional approaches.`
            ];
            
            const randomResponse = aiResponses[Math.floor(Math.random() * aiResponses.length)];
            
            aiOutput.innerHTML = `
                <h4>AI-Generated Content about "${topic}"</h4>
                <p>${randomResponse}</p>
                <div style="margin-top: 15px; padding: 10px; background: #e0f2fe; border-radius: 5px;">
                    <small><i class="fas fa-robot"></i> This content was generated by AI and should be reviewed by human experts.</small>
                </div>
            `;
        }, 2000);
    });
    
    // Contact Form Handling
    const contactForm = document.getElementById('contactForm');
    
    contactForm.addEventListener('submit', function(e) {
        e.preventDefault();
        
        // Get form data
        const formData = new FormData(contactForm);
        const name = contactForm.querySelector('input[type="text"]').value;
        
        // Simulate form submission
        contactForm.innerHTML = `
            <div style="text-align: center; padding: 30px;">
                <i class="fas fa-check-circle" style="font-size: 3rem; color: #10b981; margin-bottom: 20px;"></i>
                <h3>Thank You, ${name}!</h3>
                <p>Your message has been received. We'll get back to you within 24 hours.</p>
            </div>
        `;
    });
    
    // Add scroll effect to header
    window.addEventListener('scroll', function() {
        const header = document.querySelector('header');
        if (window.scrollY > 100) {
            header.style.boxShadow = '0 5px 20px rgba(0, 0, 0, 0.1)';
        } else {
            header.style.boxShadow = '0 2px 10px rgba(0, 0, 0, 0.1)';
        }
    });
});